### PR TITLE
Use gold linker by default if available

### PR DESCRIPTION
**Pull request by TheMarex**

### CODE REVIEW

**Comment by TheMarex** [comment]
Hm interesting. Building shared libraries with gold seems to cause errors when running the tests. I wonder why.

Also OSX seems to have ld.gold installed but the lua test fails with it?

/cc @daniel-j-h any ideas since you played around with this before?

**Comment by daniel-j-h** [comment]
Yeah I wanted to do this back [half a year ago](https://github.com/Project-OSRM/osrm-backend/pull/1647) as it allows for [debug fission](https://gcc.gnu.org/wiki/DebugFission) but could not get it to work back then (can't remember idea why). The [Webkit common CMakeLists](https://github.com/WebKit/webkit/blob/master/Source/cmake/OptionsCommon.cmake) has some great logic for it.

You also need to set the linker flags by the way. All of them (CMake has multiple vars for it).

**Comment by daniel-j-h** [comment]
`gcc5-release-shared` fails on Travis:

```
[info] Parsing in progress..
../../scripts/timer.sh: line 7: 11481 Segmentation fault      (core dumped) /bin/bash -c "$CMD"
Running osrm-contract...
../../scripts/timer.sh "osrm-contract" ../../build/osrm-contract monaco.osrm
```

Locally I'm hitting https://github.com/Project-OSRM/osrm-backend/pull/2573 as it's not in this branch.

```
/tmp/ccqg9EhU.ltrans11.ltrans.o:<artificial>:vtable for tbb::empty_task: error: undefined reference to 'tbb::empty_task::~empty_task()'
/tmp/ccqg9EhU.ltrans11.ltrans.o:<artificial>:vtable for tbb::empty_task: error: undefined reference to 'tbb::empty_task::~empty_task()'
```

Can you rebase on master and see how Travis likes it then?

**Comment by daniel-j-h** [comment]
Rebased against master. Let's see how Travis likes it now.

For the record, with gold I'm still hitting the TBB issue from above even with the https://github.com/Project-OSRM/osrm-backend/commit/61ba985bc95290f6f29f70233ff345c8e15dbc09 applied.

**Comment by daniel-j-h** [comment]
For the record, still fails with the error above with gcc 4.9.2. Works with gcc 6.1.0.

**Comment by TheMarex** [comment]
Yeah was trying to debug this locally with docker. Not sure who is at fault here.

**Comment by TheMarex** [comment]
For whatever reason gold linker and shared libraries don't work together. Tracking in https://github.com/Project-OSRM/osrm-backend/issues/2785 for now. This PR is not actionable right now.
