### ISSUE TITLE
Installation, link to boost libraries

### ISSUE THREAD

**Issue by bambax** [Project-OSRM/osrm-backend#977]
Trying to install OSRM on Debian Wheezy, can't get past this error in make:

```
Scanning dependencies of target osrm-datastore
[ 50%] Building CXX object CMakeFiles/osrm-datastore.dir/datastore.cpp.o
Linking CXX executable osrm-datastore
/tmp/cc9eMZux.lto.o: In function `_ZN12OSRMLockFileclEv.isra.149.13169':
datastore.cpp.o:(.text+0x3ef0): undefined reference to  `boost::filesystem::detail::temp_directory_path(boost::system::error_code*)'
```

followed by lots of other undefined reference errors...

Boost 1.54.0 is in /usr/local/lib/ and cmake is run like this: `cmake -DBOOST_ROOT=/usr/local/lib/ ..` 

What can I do?

**Comment by fdimushka** [comment]
I do make
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Building on a 64 bit system
-- Configuring OSRM in release mode
-- Performing Test HAS_LTO_FLAG
-- Performing Test HAS_LTO_FLAG - Success
-- Using gcc specific binutils for LTO.
-- Performing Test HAS_COLOR_FLAG
-- Performing Test HAS_COLOR_FLAG - Success
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   unit_test_framework
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Intel TBB
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so  
-- Found Luabind: /usr/lib/libluabind.so
-- Found Lua52: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so  
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR) 
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Failed
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
-- Found Lua51: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.1.5") 
-- Looking for LuaJIT 5.1
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR) 
-- Performing Test LUABIND51_WORKS
-- Performing Test LUABIND51_WORKS - Success
-- Luabind works with Lua 5.1 at /usr/lib/x86_64-linux-gnu/liblua5.1.so
-- Found EXPAT: /usr/lib/x86_64-linux-gnu/libexpat.so (found version "2.1.0") 
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so  
-- Found STXXL: /usr/lib/libstxxl.so
-- Looking for OSMPBF...
-- Found OSMPBF: /usr/local/lib/libosmpbf.a  
-- Found OSMPBF: /usr/local/lib/libosmpbf.a
-- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Project-OSRM/build

I receive an error: 
Linking CXX executable osrm-extract
/usr/bin/ld: CMakeFiles/osrm-extract.dir/extractor/extraction_containers.cpp.o: undefined reference to symbol 'omp_get_max_threads@@OMP_1.0'
//usr/lib/x86_64-linux-gnu/libgomp.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/osrm-extract.dir/build.make:268: recipe for target 'osrm-extract' failed
make[2]: *** [osrm-extract] Error 1
CMakeFiles/Makefile2:555: recipe for target 'CMakeFiles/osrm-extract.dir/all' failed
make[1]: *** [CMakeFiles/osrm-extract.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Thanks!)
P.s. libgomp installed

**Comment by DennisOSRM** [comment]
should be fixed in latest develop branch.
