### ISSUE TITLE
Can't build in ArchLinux

### ISSUE THREAD

**Issue by imShara** [Project-OSRM/osrm-backend#1510]
Here is `cmake ..` output:

```
-- Building on a 64 bit system
-- Configuring OSRM in release mode
-- LTO working
-- Using gcc specific binutils for LTO.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   unit_test_framework
-- Found Intel TBB
-- Looking for Luabind...
-- Found Luabind: /usr/lib64/libluabind.so
-- Looking for LuaJIT 5.2
-- Found LuaJIT: /usr/lib64/libluajit-5.1.so
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Failed
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
-- Looking for LuaJIT 5.1
-- Found LuaJIT: /usr/lib64/libluajit-5.1.so
-- Performing Test LUABIND51_WORKS
-- Performing Test LUABIND51_WORKS - Failed
CMake Error at cmake/check_luabind.cmake:38 (message):
  Luabind does not work with Lua 5.1 at /usr/lib64/liblua5.1.so, no working
  Luabind found
Call Stack (most recent call first):
  CMakeLists.txt:251 (include)


-- Configuring incomplete, errors occurred!
```

## Installed packages: 
**Official:** [luajit](https://www.archlinux.org/packages/?sort=&q=luajit)
**AUR:** [luabind](https://aur.archlinux.org/packages/luabind/)

**Comment by TheMarex** [comment]
Try this version of luabind https://github.com/DennisOSRM/luabind

**Comment by imShara** [comment]
TheMarex, how to build this? There is no Jamfile.

*offtop: Why you disable bicycle router on map.project-osrm.org?*

**Comment by TheMarex** [comment]
@imShara we never had bicycle routing on `map.project-osrm.org`. It is only a demo server that runs the unstable version from the `develop` branch of OSRM.

**Comment by skraelings** [comment]
@imShara I managed to build luabind from this repo with:
sudo bjam release toolset=gcc  --prefix /usr/local install

**Comment by imShara** [comment]
@skraelings, you are right, [Pavlik's luabind](https://github.com/rpavlik/luabind) working and exists in aur as [liabind-git](https://aur.archlinux.org/packages/luabind-git/).

But here is another error:
```
[ 76%] Building CXX object CMakeFiles/osrm-extract.dir/extractor/extractor.cpp.o
Linking CXX executable osrm-extract
/tmp/ccwU9Owx.ltrans2.ltrans.o: In function `RestrictionParser::ReadRestrictionExceptions(lua_State*)':
<artificial>:(.text+0xd95): undefined reference to `lua_rotate'
```

**Comment by skraelings** [comment]
@imShara I tried those in aur and neither worked, ultimately I cloned Pavlik's repository and built from it.

**Comment by guyvdb** [comment]
I have followed along with your process on arch. I have built the following from source:

luabind from rpavlik github repo
  sudo bjam release toolset=gcc --prefix=/usr/local install

libxstxxl from http://sourceforge.net/projects/stxxl/files/stxxl/1.4.1/stxxl-1.4.1.tar.gz/download
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON

libosmpfb
https://github.com/scrosby/OSM-binary/archive/v1.3.3.zip

I am am also now not able to build OSRM. When linking osrm-extract I get an undefined reference to undefined reference to `lua_rotate'

Linking CXX executable osrm-extract
/tmp/ccDKx36I.ltrans27.ltrans.o: In function `RestrictionParser::ReadRestrictionExceptions(lua_State*)':
<artificial>:(.text+0x4c32): undefined reference to `lua_rotate'
collect2: error: ld returned 1 exit status
CMakeFiles/osrm-extract.dir/build.make:271: recipe for target 'osrm-extract' failed
make[2]: *** [osrm-extract] Error 1
CMakeFiles/Makefile2:636: recipe for target 'CMakeFiles/osrm-extract.dir/all' failed
make[1]: *** [CMakeFiles/osrm-extract.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fpacheco** [comment]
It's very strange, lua_rotate is present only in lua 5.3:
```
readelf -Ws /usr/lib/liblua.so.5.1 | grep lua_rotate
readelf -Ws /usr/lib/liblua.so.5.2 | grep lua_rotate
readelf -Ws /usr/lib/liblua.so.5.3 | grep lua_rotate
```
/usr/include/lua.h (5.3) have lua_rotate. 
/usr/include/5.2/lua.h dont have lua_rotate.
  
I think, something is using 5.3 header (/usr/include/lua.h) and then, try to be linked with 5.2/5.1 library.

**Comment by fpacheco** [comment]
Quick and dirty recipe to compile OSRM (develop branch) in Archlinux:
+ backup current Lua headers (version 5.3, in /usr/include): lauxlib.h  lua.h  lua.hpp  luaconf.h  lualib.h;
+ copy 5.2 headers from /usr/include/5.2 to /usr/include
+ compile OSRM;
+ restore original headers (version 5.3, to /usr/include).

This works in my (current) Archlinux. Best regards. Fernando.

**Comment by daniel-j-h** [comment]
Our CMake module can handle Lua 5.1 and Lua 5.2 --- if nothing else works, do a local Lua build and tell it CMake; the packaged luabind is most probably the one from 2010, since the maintainers never made an official release after that; please compile luabind from source in that case, as described above. Make sure luabind links against the same Lua version that you are using in osrm-backend; check that e.g. with

    ldd libluabind.so
