### PR TITLE
Remove include that breaks compilation for Boost v1.85.0

### LINKED ISSUE #6850: Build failure with Boost 1.85.0 due to convenience.hpp removal
# Issue

OSRM does not build with Boost 1.85.0 due to usage of removed `convenience.hpp` header (https://github.com/boostorg/filesystem/commit/5df060e95ca844fe91b29001b4ae22bdb65635c6):
https://github.com/Project-OSRM/osrm-backend/blob/7ebd21f39e32640e0d40b893d228350f218085ad/include/util/lua_util.hpp#L11

```
/tmp/osrm-backend-20240425-65409-ai2urn/osrm-backend-5.27.1/include/util/lua_util.hpp:11:10: fatal error: 'boost/filesystem/convenience.hpp' file not found
#include <boost/filesystem/convenience.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

I think `boost::filesystem::canonical` is part of https://www.boost.org/doc/libs/1_85_0/boost/filesystem/operations.hpp. Switching `convenience.hpp` to `operations.hpp` allows build to succeed. Not sure how this impacts older Boost versions.

# Steps to reproduce

Please provide the steps required to reproduce your problem.
- `osrm-backend` version being used - 5.27.1
- OSM extract that was processed - n/a
- Processing commands (e.g. CH vs MLD processing) - n/a
- Server queries - n/a

Should hit error when compiling with Boost 1.85.0.

# Specifications

Please provide details of your development environment.
- Library/dependency versions - building for Homebrew, so can see exact versions at https://formulae.brew.sh/formula/osrm-backend#default
- Operating system - macOS Monterey & Ventura & Sonoma and Linux Ubuntu 22.04
- Hardware - x86_64-based macOS, arm64 (Apple Silicon)-based macOS, and x86_64-based Linux (GitHub runner)

Seen when updating Boost in Homebrew (https://github.com/Homebrew/homebrew-core/pull/169237) across the matrix of all platforms supported.

### PR DESCRIPTION
**Pull request by DennisOSRM**
Fixes #6850

### CODE REVIEW

**Review by SiarheiFedartsou — APPROVED** [review]

**Comment by DennisOSRM** [comment]
Note: This also requires an update to the version of the boost lib in Conan.
