### ISSUE TITLE
build fails on mac 10.9, seems related to luabind

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#767]
After upgrading to 10.9 i did a 'brew upgrade' and removed the build folder. But building the latest develop branch fails: 

```
~/code/Project-OSRM$ (develop) git log -n 1
commit 67c5e3966aa93d43191d745aec68689b95320f28
Author: Emil Tin <emil.tin@tmf.kk.dk>
Date:   Fri Oct 18 18:33:56 2013 +0200

    fix some indentation and spelling

~/code/Project-OSRM$ (develop) rake
-- System supports 64 bits.
-- Configuring OSRM in release mode
-- OpenMP parallelization not available using clang++
Set Architecture to x64 on OS X
-- DARWIN_VERSION=13
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   regex
--   system
--   thread
-- Looking for LuaJIT...
-- Could NOT find LuaJIT (missing:  LUAJIT_LIBRARIES) 
-- Looking for Luabind...
-- Found Luabind: /usr/local/lib/libluabind.dylib
-- Looking for STXXL...
-- Found STXXL: /usr/local/lib/libstxxl.a
-- Looking for OSMPBF...
-- Found OSMPBF: /usr/local/lib/libosmpbf.a
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/emil/code/Project-OSRM/build
[...]
[ 63%] Building CXX object CMakeFiles/osrm-extract.dir/Extractor/ScriptingEnvironment.cpp.o
/Users/emil/code/Project-OSRM/Extractor/ScriptingEnvironment.cpp:100:14: error: no matching member function for call to 'def'
            .def("Add", &std::vector<std::string>::push_back)
            ~^~~
/usr/local/include/luabind/class.hpp:571:11: note: candidate template ignored: couldn't infer template argument 'F'
                class_& def(const char* name, F f)
                        ^
/usr/local/include/luabind/class.hpp:603:11: note: candidate template ignored: failed template argument deduction
                class_& def(constructor<BOOST_PP_ENUM_PARAMS(LUABIND_MAX_ARITY, A)> sig, const Policies& policies)
                        ^
/usr/local/include/luabind/class.hpp:722:11: note: candidate template ignored: failed template argument deduction
                class_& def(detail::operator_<Derived>, Policies const& policies)
                        ^
/usr/local/include/luabind/class.hpp:580:11: note: candidate function template not viable: requires 3 arguments, but 2 were provided
                class_& def(char const* name, F fn, DefaultOrPolicies default_or_policies)
                        ^
/usr/local/include/luabind/class.hpp:588:11: note: candidate function template not viable: requires 4 arguments, but 2 were provided
                class_& def(char const* name, F fn
                        ^
/usr/local/include/luabind/class.hpp:597:11: note: candidate function template not viable: requires single argument 'sig', but 2 arguments were provided
                class_& def(constructor<BOOST_PP_ENUM_PARAMS(LUABIND_MAX_ARITY, A)> sig)
                        ^
/usr/local/include/luabind/class.hpp:732:11: note: candidate function template not viable: requires 1 argument, but 2 were provided
                class_& def(detail::operator_<Derived>)
                        ^
1 error generated.
make[2]: *** [CMakeFiles/osrm-extract.dir/Extractor/ScriptingEnvironment.cpp.o] Error 1
make[1]: *** [CMakeFiles/osrm-extract.dir/all] Error 2
make: *** [all] Error 2

~/code/Project-OSRM$ (develop) brew info luabind
luabind: stable 0.9.1
http://www.rasterbar.com/products/luabind.html
/usr/local/Cellar/luabind/0.9.1 (83 files, 612K) *
  Built from source
From: https://github.com/mxcl/homebrew/commits/master/Library/Formula/luabind.rb
==> Dependencies
Build: boost-build
Required: lua, boost
```

luabind was also at version 0.9.1 before.
