### ISSUE TITLE
Extractor/ScriptingEnvironment.cpp:95: error: no matching function for call to luabind

### ISSUE THREAD

**Issue by JanisE** [Project-OSRM/osrm-backend#535]
Hello!

I've been trying to install OSRM on my Gentoo for some time now. At the moment I'm getting this error:
"Extractor/ScriptingEnvironment.cpp:95: error: no matching function for call to 'luabind::class_<_Way, luabind::detail::unspecified, luabind::detail::unspecified, luabind::detail::unspecified>::def_readwrite(const char [10], _Way::<anonymous enum> _Way::*)'"

I have luabind version 0.9 installed, modified to get rid of #elif directives (an issue with Boost 1.49). Could it be an issue with luabind or something else?

Thanks!

**Comment by hungtv31** [comment]
Hello DennisOSRM,
I build on gcc 4.4.7-11 and luabind 9.1.4.
I have error when build

g++ -o Extractor/ScriptingEnvironment.o -c -minline-all-stringops -fopenmp -O3 -DNDEBUG -I/home/viettelmap/setup/OSRM/stxxl-1.3.1/include -I/usr/include -I/usr/include/include -I/usr/include/libxml2 -I/usr/include/lua5.1 Extractor/ScriptingEnvironment.cpp
Extractor/ScriptingEnvironment.cpp: In constructor 'ScriptingEnvironment::ScriptingEnvironment(const char*)':
Extractor/ScriptingEnvironment.cpp:96: error: no matching function for call to 'luabind::class_<_Way, luabind::detail::unspecified, luabind::detail::unspecified, luabind::detail::unspecified>::def_readwrite(const char [10], _Way::<anonymous enum> _Way::*)'
scons: *** [Extractor/ScriptingEnvironment.o] Error 1
scons: building terminated because of errors.

Help me!

**Comment by DennisOSRM** [comment]
Try using a newer compiler. GCC 4.4x doesn't support C++11. Version 4.8 and beyond should be fine or use clang.

**Comment by hungtv31** [comment]
Dear DennisOSRM
I user gcc 4.8 and rebuild but have erroor:

[root@CentOS6 OSRM]# scons --no-march --stxxl=/u01/OSRM/stxxl-1.3.1
scons: Reading SConscript files ...
Using default C++ Compiler:  g++
Default platform
STXXLROOT =  /u01/OSRM/stxxl-1.3.1
Checking for C++ library pthread... yes
Checking for C++ library luajit-5.1... (cached) no
luajit library not found. Checking for interpreter
Checking for C header file omp.h... yes
Checking for C++ library bz2... yes
Checking for C++ library osmpbf... yes
Checking for C++ library protobuf... yes
Checking for Protobuffer version >= 2.3.0... yes
Checking for C++ library stxxl... yes
Checking for C++ library xml2... yes
Checking for C++ library z... yes
Checking for Boost version >= 1.44... yes
Checking for C++ library boost_system... yes
Checking for C++ library boost_thread... yes
Checking for C++ library boost_regex... yes
Checking for C++ library boost_filesystem... yes
Checking for C++ header file boost/archive/iterators/base64_from_binary.hpp... yes
Checking for C++ header file boost/archive/iterators/binary_from_base64.hpp... yes
Checking for C++ header file boost/archive/iterators/transform_width.hpp... yes
Checking for C++ header file boost/bind.hpp... yes
Checking for C++ header file boost/circular_buffer.hpp... yes
Checking for C++ header file boost/enable_shared_from_this.hpp... yes
Checking for C++ header file boost/foreach.hpp... yes
Checking for C++ header file boost/lexical_cast.hpp... yes
Checking for C++ header file boost/logic/tribool.hpp... yes
Checking for C++ header file boost/math/tr1.hpp... yes
Checking for C++ header file boost/noncopyable.hpp... (cached) yes
Checking for C++ header file boost/property_tree/ptree.hpp... yes
Checking for C++ header file boost/property_tree/ini_parser.hpp... yes
Checking for C++ header file boost/shared_ptr.hpp... yes
Checking for C++ header file boost/thread/mutex.hpp... yes
Checking for C++ header file boost/thread/thread.hpp... yes
Checking for C++ header file boost/thread/condition.hpp... yes
Checking for C++ header file boost/thread/thread.hpp... yes
Checking for C++ header file boost/thread.hpp... yes
Checking for C++ header file boost/tuple/tuple.hpp... yes
Checking for C++ header file boost/unordered_map.hpp... yes
scons: done reading SConscript files.
scons: Building targets ...
g++ -o Algorithms/CRC32.o -c -minline-all-stringops -fopenmp -O3 -DNDEBUG -I/u01/OSRM/stxxl-1.3.1/include -I/usr/include -I/usr/include/include -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/lua5.1 Algorithms/CRC32.cpp
g++ -o Contractor/EdgeBasedGraphFactory.o -c -minline-all-stringops -fopenmp -O3 -DNDEBUG -I/u01/OSRM/stxxl-1.3.1/include -I/usr/include -I/usr/include/include -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/lua5.1 Contractor/EdgeBasedGraphFactory.cpp
g++ -o Contractor/TemporaryStorage.o -c -minline-all-stringops -fopenmp -O3 -DNDEBUG -I/u01/OSRM/stxxl-1.3.1/include -I/usr/include -I/usr/include/include -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/lua5.1 Contractor/TemporaryStorage.cpp
g++ -o Descriptors/DescriptionFactory.o -c -minline-all-stringops -fopenmp -O3 -DNDEBUG -DROUTED -I/u01/OSRM/stxxl-1.3.1/include -I/usr/include -I/usr/include/include -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/lua5.1 Descriptors/DescriptionFactory.cpp
g++ -o Extractor/ExtractionContainers.o -c -minline-all-stringops -fopenmp -O3 -DNDEBUG -I/u01/OSRM/stxxl-1.3.1/include -I/usr/include -I/usr/include/include -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/lua5.1 Extractor/ExtractionContainers.cpp
g++ -o Extractor/ExtractorCallbacks.o -c -minline-all-stringops -fopenmp -O3 -DNDEBUG -I/u01/OSRM/stxxl-1.3.1/include -I/usr/include -I/usr/include/include -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/lua5.1 Extractor/ExtractorCallbacks.cpp
g++ -o Extractor/ScriptingEnvironment.o -c -minline-all-stringops -fopenmp -O3 -DNDEBUG -I/u01/OSRM/stxxl-1.3.1/include -I/usr/include -I/usr/include/include -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/lua5.1 Extractor/ScriptingEnvironment.cpp
Extractor/ScriptingEnvironment.cpp: In constructor 'ScriptingEnvironment::ScriptingEnvironment(const char*)':
Extractor/ScriptingEnvironment.cpp:96: error: no matching function for call to 'luabind::class_<_Way, luabind::detail::unspecified, luabind::detail::unspecified, luabind::detail::unspecified>::def_readwrite(const char [10], _Way::<anonymous enum> _Way::*)'
scons: *** [Extractor/ScriptingEnvironment.o] Error 1
scons: building terminated because of errors.
[root@CentOS6 OSRM]# g++ --version
g++ (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Help me.
