### ISSUE TITLE
Can't compile OSRM 6.0 for Debian 12 bookworm

### ISSUE THREAD

**Issue by simwin** [Project-OSRM/osrm-backend#7195]
# Issue
Can't compile OSRM 6.0 for Debian 12 bookworm

[ 66%] Building CXX object CMakeFiles/SERVER.dir/src/server/connection.cpp.o
In file included from /usr/include/boost/asio.hpp:23,
                 from /home/sv/install/osrmLua5.3/osrm-backend/include/server/http/reply.hpp:6,
                 from /home/sv/install/osrmLua5.3/osrm-backend/include/server/connection.hpp:5,
                 from /home/sv/install/osrmLua5.3/osrm-backend/src/server/connection.cpp:1:
/usr/include/boost/asio/awaitable.hpp: In constructor ‘boost::asio::awaitable<T, Executor>::awaitable(boost::asio::awaitable<T, Executor>&&)’:
/usr/include/boost/asio/awaitable.hpp:68:19: error: ‘exchange’ is not a member of ‘std’; did you mean ‘std::__atomic_impl::exchange’?
   68 |     : frame_(std::exchange(other.frame_, nullptr))
      |                   ^~~~~~~~
In file included from /usr/include/c++/12/bits/shared_ptr_atomic.h:33,
                 from /usr/include/c++/12/memory:78,
                 from /usr/include/boost/asio/associated_allocator.hpp:19,
                 from /usr/include/boost/asio.hpp:20:
/usr/include/c++/12/bits/atomic_base.h:976:7: note: ‘std::__atomic_impl::exchange’ declared here
  976 |       exchange(_Tp* __ptr, _Val<_Tp> __desired, memory_order __m) noexcept
      |       ^~~~~~~~
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/date_time/time_clock.hpp:17,
                 from /usr/include/boost/date_time/posix_time/posix_time_types.hpp:10,
                 from /usr/include/boost/asio/time_traits.hpp:23,
                 from /usr/include/boost/asio/detail/timer_queue_ptime.hpp:22,
                 from /usr/include/boost/asio/detail/deadline_timer_service.hpp:29,
                 from /usr/include/boost/asio/basic_deadline_timer.hpp:25,
                 from /usr/include/boost/asio.hpp:25:
/usr/include/boost/bind.hpp: At global scope:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-ambiguous-reversed-operator’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-deprecated-comma-subscript’ may have been intended to silence earlier diagnostics
gmake[2]: *** [CMakeFiles/SERVER.dir/build.make:104: CMakeFiles/SERVER.dir/src/server/connection.cpp.o] Ошибка 1
gmake[1]: *** [CMakeFiles/Makefile2:446: CMakeFiles/SERVER.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

# Steps to reproduce

sudo apt-get install git g++ cmake libboost-dev libboost-filesystem-dev libboost-thread-dev libboost-system-dev libboost-regex-dev libxml2-dev libsparsehash-dev libbz2-dev zlib1g-dev libzip-dev libgomp1 pkg-config libgdal-dev libboost-program-options-dev libboost-iostreams-dev libboost-test-dev libtbb-dev libexpat1-dev liblua5.4-dev libboost-all-dev

git clone https://github.com/Project-OSRM/osrm-backend.git
cd osrm-backend/
mkdir -p build
cd build
cmake ..
cmake --build .

# Specifications

- Operating system Debian 12 64 bit
- Hardware CPU i7-6700k, 32 Gb RAM

**Comment by phoenixproject** [comment]
- Debian 12 and Ubuntu 24 do not work with versions 6.0.0, 5.27.0, 5.26.0, 5.25.0, 5.24.0.
- Debian 11 does not work with versions 6.0.0, 5.27.0.
- **Debian 11 works with versions 5.26.0, 5.25.0, and 5.24.0.**

I just compiled all these versions on all these operating systems and went back to **Debian 11 with OSRM version 5.26.0**.

Debian 11 likely has development toolchains that are historically more compatible with OSRM versions.

**Comment by TommiKabelitz** [comment]
I ran into the same error (`/usr/include/boost/asio/awaitable.hpp:68:19: error: ‘exchange’ is not a member of ‘std’;`) when compiling for Mint 21.3 (Ubuntu 22). I think it is some issue in boost itself with a missing import in `awaitable.hpp`. If memory serves, the version installed by apt was 1.74 and it got fixed a few versions later. I got OSRM to build by updating boost a to newer version. I added a PPA because I couldn't be bothered building boost from source, but you definitely could do that.

**Comment by DennisOSRM** [comment]
Enabling conan should fix this issue as it pulls in a well tested version of boost.

**Comment by DennisOSRM** [comment]
just a quick update on this.

I can confirm that compiling the latest master branch on Debian 13 now works successfully with the stock system packages, and also when using the Conan-based dependencies.

Since everything builds fine on my side, I am going to close this issue now. Thanks everyone for the work on this!
