### PR TITLE
Refactor post-processing and add test for turn location

### PR DESCRIPTION
**Pull request by MoKob**
# Issue

Works towards https://github.com/Project-OSRM/osrm-backend/issues/3158 and https://github.com/Project-OSRM/osrm-backend/issues/3293 

## Tasklist
 - [x] remove all debug output
 - [x] clean-up scenarios
 - [x] review
 - [x] adjust for comments

## Requirements / Relations
 Link any requirements here. Other pull requests this PR is based on?

### Guide:

- The refactor fixes an issue that prevented new-names from being suppressed when they are shorter than 100 meters. This was in before, but didn't work apparently. Many tests are adjusted for this in one of two ways:
  - added a given a grid size of 200 meters (possible if tests only rely on shape, not on lengths)
  - removed additional road names from `route` field
- I removed collapse considerations from `lane processing`. Lane processing should not handle collapse functionality. Collapse should run after lane processing and consider lanes to decide if collapse is possible.
- many tests are given the `locations` check as well, especially for collapse scenarios
- to avoid thresholds that are too large, many cases require lanes to check for road widths now

### CODE REVIEW

File: src/engine/guidance/collapse_turns.cpp [hunk 1]
```diff
@@ -0,0 +1,271 @@
...
+        util::angleBetweenBearings(entry_step_entry_bearing, exit_step_exit_bearing);
+    // We allow for minor deviations from a straight line
+    if (((entry_step.distance < MAX_COLLAPSE_DISTANCE && exit_step.intersections.size() == 1) ||
+         (entry_angle <= 185 && exit_angle <= 185) || (entry_angle >= 175 && exit_angle >= 175)) &&
+        angularDeviation(total_angle, 180) > 20)
+    {
+        // both angles are in the same direction, the total turn gets increased
+        //
+        // a ---- b
+        //           \
```
Comment (oxidase) [inline src/engine/guidance/collapse_turns.cpp]: Not really a code change, but for `collapse_turns.cpp:61:9: warning: multi-line comment [-Wcomment]` it is possible to put a NO-BREAK SPACE character 0xA0 ' '. It will not be removed as a trailing white space, is invisible and suppresses the warning. The same for `src/engine/guidance/post_processing.cpp:343:9: warning: multi-line comment [-Wcomment]`

**Comment by daniel-j-h** [comment]
Note: test case for collapsing away signage data is here https://github.com/Project-OSRM/osrm-backend/pull/3097 - could potentially be included here.

File: features/guidance/turn.feature [hunk 2]
```diff
@@ -1156,12 +1156,12 @@ Feature: Simple Turns
...
-                  |   |     i
+                  |   |  '-i
+                  |   |
             a_    |   |
                ''.b---c
-                  |   |'d._
-                  |   |    'e
+                  |   |' d._
+                  |   |     'e
                   j   k
```
Comment (MoKob) [inline features/guidance/turn.feature]: I had the choice to try and hack something into the engine to possibly detect other cases like. Since the original situation works just fine (see screenshot), I opted to reduce the severity of this turn to ensure that I don't spent ages on unnecessary optimisation.
screen shot 2017-01-26 at 16 41 14

File: features/bicycle/bridge.feature [hunk 3]
```diff
@@ -45,7 +45,7 @@ Feature: Bicycle - Handle cycling
 
         When I route I should get
             | from | to | route           | modes                           | speed  |
-            | a    | g  | abc,cde,efg,efg | cycling,cycling,cycling,cycling | 5 km/h |
-            | b    | f  | abc,cde,efg,efg | cycling,cycling,cycling,cycling | 4 km/h |
+            | a    | g  | abc,cde,efg,efg | cycling,cycling,cycling,cycling | 6 km/h |
+            | b    | f  | abc,cde,efg,efg | cycling,cycling,cycling,cycling | 5 km/h |
```
Comment (MoKob) [inline features/bicycle/bridge.feature]: longer ways -> better average speed

File: features/car/bridge.feature [hunk 4]
```diff
@@ -44,8 +45,8 @@ Feature: Car - Handle driving
             | efg   | primary |         |          |
 
         When I route I should get
-            | from | to | route           | modes                           | speed  |
-            | a    | g  | abc,cde,efg,efg | driving,driving,driving,driving | 6 km/h |
-            | b    | f  | abc,cde,efg,efg | driving,driving,driving,driving | 4 km/h |
-            | c    | e  | cde,cde         | driving,driving                 | 2 km/h |
-            | e    | c  | cde,cde         | driving,driving                 | 2 km/h |
+            | from | to | route           | modes                           | speed   |
+            | a    | g  | abc,cde,efg,efg | driving,driving,driving,driving | 12 km/h |
```
Comment (MoKob) [inline features/car/bridge.feature]: longer ways -> less impact of turn penalties -> better speed

File: features/guidance/merge-segregated-roads.feature [hunk 5]
```diff
@@ -501,25 +501,25 @@ Feature: Merge Segregated Roads
...
-            | restriction | xb       | bc     | b        | no_left_turn |
-            | restriction | xc       | cf     | c        | no_left_turn |
-            | restriction | xf       | fg     | f        | no_left_turn |
-            | restriction | xg       | gb     | g        | no_left_turn |
+            | type        | way:from | way:to | node:via | restriction      |
+            | restriction | bc       | cf     | c        | no_left_turn     |
+            | restriction | fg       | gb     | g        | no_left_turn     |
+            | restriction | gb       | bc     | b        | no_left_turn     |
+            | restriction | cf       | fg     | f        | no_left_turn     |
+            | restriction | xb       | xf     | x        | only_straight_on |
```
Comment (MoKob) [inline features/guidance/merge-segregated-roads.feature]: change paradigm to more easily give correct turn restrictions

File: features/guidance/merge-segregated-roads.feature [hunk 6]
```diff
@@ -501,25 +501,25 @@ Feature: Merge Segregated Roads
...
+            | restriction | xc       | xg     | x        | only_straight_on |
 
         # the goal here should be not to mention the intersection in the middle at all and also suppress the segregated parts
         When I route I should get
-            | waypoints | route            | intersections																																   |
-            | a,l       | horiz,vert,vert  | true:90;false:0 true:60 true:90 true:180 false:270,true:60 true:120 false:240 true:300,true:0 false:90 false:180 false:240 false:270;true:180 |
-            | a,d       | horiz,horiz      | true:90,false:0 true:60 true:90 true:180 false:270,false:0 true:90 false:180 false:270 true:300;true:270									   |
-            | j,h       | vert,horiz,horiz | true:0;true:0 true:90 false:180 false:270 true:300,true:60 false:120 true:240 true:300,false:0 false:90 false:120 false:180 true:270;true:90  |
-            | j,l       | vert,vert        | true:0,true:0 true:90 false:180 false:270 true:300,true:0 false:90 false:180 true:240 false:270;true:180									   |
+            | waypoints | route            | intersections																																    |
```
Comment (MoKob) [inline features/guidance/merge-segregated-roads.feature]: all due to the now correct turn restrictions

**Comment by TheMarex** [comment]
Rebased to fix the merge conflicts caused by merging #3628 but getting the following build errors locally with GCC 6:

```
/home/patrick/Code/osrm-backend/src/engine/guidance/post_processing.cpp: In function ‘std::vector<osrm::engine::guidance::RouteStep> osrm::engine::guidance::postProcess(std::vector<osrm::engine::guidance::RouteStep>)’:
/home/patrick/Code/osrm-backend/src/engine/guidance/post_processing.cpp:261:38: error: reference to ‘TurnType’ is ambiguous
         else if (instruction.type == TurnType::StayOnRoundabout)
                                      ^~~~~~~~
/home/patrick/Code/osrm-backend/src/engine/guidance/post_processing.cpp:24:57: note: candidates are: namespace TurnType = osrm::extractor::guidance::osrm::extractor::guidance::TurnType;
 namespace TurnType = osrm::extractor::guidance::TurnType;

```

File: include/extractor/guidance/sliproad_handler.hpp [hunk 7]
```diff
@@ -65,6 +65,11 @@ class SliproadHandler final : public IntersectionHandler
                              const IntersectionViewData &first,
                              const IntersectionViewData &second) const;
 
+    // check if no mode changes are involved
+    bool allSameMode(const EdgeID in_road,
```
Comment (MoKob) [inline include/extractor/guidance/sliproad_handler.hpp]: fixes a problem in sliproad handling, since we didn't check for this before

File: src/engine/guidance/collapse_scenario_detection.cpp [hunk 8]
```diff
@@ -0,0 +1,404 @@
...
+    const auto is_short = link_step.distance <= MAX_LINK_ROAD_LENGTH;
+    const auto unnamed = link_step.name_id == EMPTY_NAMEID;
+    const auto between_named =
+        (pre_link_step.name_id != EMPTY_NAMEID) && (post_link_step.name_id != EMPTY_NAMEID);
+
+    return is_short && unnamed && between_named && noIntermediaryIntersections(link_step);
+}
+
+// Just like a link step, but shorter and no name restrictions.
+bool isCollapsableSegment(const RouteStep &step)
```
Comment (MoKob) [inline src/engine/guidance/collapse_scenario_detection.cpp]: Carrying over from https://github.com/Project-OSRM/osrm-backend/pull/3705#pullrequestreview-21548743, the name of this function should be made a bit clearer.

File: src/engine/guidance/collapse_scenario_detection.cpp [hunk 9]
```diff
@@ -55,7 +55,7 @@ bool isLinkroad(const RouteStep &pre_link_step,
 }
 
 // Just like a link step, but shorter and no name restrictions.
-bool isCollapsableSegment(const RouteStep &step)
+bool isShortAndUndisturbed(const RouteStep &step)
```
Comment (daniel-j-h) [inline src/engine/guidance/collapse_scenario_detection.cpp]: Thanks!

**Comment by TheMarex** [comment]
@daniel-j-h @oxidase was this reviewed?

**Comment by daniel-j-h** [comment]
No.

**Comment by MoKob** [comment]
@oxidase sure. distance is not the best measure here. The full guidance system is only reasonable for car as of now. So we need a complete overhaul here.
