### PR TITLE
Make rounding when computing PhantomNode weight symmetric

### LINKED ISSUE #3038: Different durations returned for reverse and forward routes
I noticed this while logging cucumber tests for https://github.com/Project-OSRM/osrm-backend/issues/3036

Routing on a test case where a way is set to
- one road class type
- not a one way

Expected outcome is that a route between two ponits on the way in either direction should return the same duration, but this is not the case. All the cases I've seen so far only differ by `0.1s`.

Specifically this test, [speed.feature](https://github.com/Project-OSRM/osrm-backend/blob/6cf99c886fcb42c4e417f5477ed2c9d2eebb5554/features/car/speed.feature)

### LINKED ISSUE #3088: Windows builds are broken
```
C:\projects\osrm\osrm-deps\boost\include\boost-1_59\boost/mpl/eval_if.hpp(41): error C2504: 'boost::result_of<const UnaryFunc (unsigned int &)>': base class undefined [C:\projects\osrm\build\ENGINE.vcxproj]
```

This was broken by #3015.

### PR DESCRIPTION
**Pull request by TheMarex**
# Issue

Fixes #3038.

## Tasklist
 - [x] review
 - [x] adjust for comments

### CODE REVIEW

File: include/engine/geospatial_query.hpp [hunk 1]
```diff
@@ -400,7 +400,8 @@ template <typename RTreeT, typename DataFacadeT> class GeospatialQuery
         }
         if (data.reverse_segment_id.id != SPECIAL_SEGMENTID)
         {
-            reverse_weight *= 1.0 - ratio;
+            EdgeWeight difference = reverse_weight * ratio;
```
Comment (MoKob) [inline include/engine/geospatial_query.hpp]: can be `const`.

**Comment by MoKob** [comment]
Minor nitpick, otherwise fine.

**Comment by daniel-j-h** [comment]
- [ ] needs to adapt Cucumber tests to see the fix in action.
