### ISSUE TITLE
Error while compiling OSRM-backend

### ISSUE THREAD

**Issue by Rza-A** [Project-OSRM/osrm-backend#6494]
I am trying to build OSRM on Ubuntu 20.4. I have installed the following dependencies:

`build-essential git cmake pkg-config doxygen libboost-all-dev libtbb-dev lua5.2 liblua5.2-dev libluabind-dev libstxxl-dev libstxxl1v5 libxml2 libxml2-dev libosmpbf-dev libbz2-dev libzip-dev libprotobuf-dev`

when I issue the `make` command I get the following error:

```
[ 78%] Built target SERVER
[ 82%] Building C object CMakeFiles/MICROTAR.dir/third_party/microtar/src/microtar.c.o
[ 82%] Built target MICROTAR
[ 82%] Building CXX object CMakeFiles/osrm.dir/src/osrm/osrm.cpp.o
[ 82%] Linking CXX static library libosrm.a
[ 82%] Built target osrm
[ 82%] Building CXX object CMakeFiles/osrm-routed.dir/src/tools/routed.cpp.o
In file included from /home/linuxbrew/.linuxbrew/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /home/linuxbrew/.linuxbrew/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /home/linuxbrew/.linuxbrew/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /home/linuxbrew/.linuxbrew/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /home/linuxbrew/.linuxbrew/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /home/linuxbrew/.linuxbrew/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /home/linuxbrew/.linuxbrew/include/boost/shared_ptr.hpp:17,
                 from /home/linuxbrew/.linuxbrew/include/boost/date_time/time_clock.hpp:17,
                 from /home/linuxbrew/.linuxbrew/include/boost/date_time/posix_time/posix_time_types.hpp:10,
                 from /home/linuxbrew/.linuxbrew/include/boost/asio/time_traits.hpp:23,
                 from /home/linuxbrew/.linuxbrew/include/boost/asio/detail/timer_queue_ptime.hpp:22,
                 from /home/linuxbrew/.linuxbrew/include/boost/asio/detail/deadline_timer_service.hpp:31,
                 from /home/linuxbrew/.linuxbrew/include/boost/asio/basic_deadline_timer.hpp:25,
                 from /home/linuxbrew/.linuxbrew/include/boost/asio.hpp:29,
                 from /home/reza/projects/mobility_simulator/osrm-backend/include/server/http/reply.hpp:6,
                 from /home/reza/projects/mobility_simulator/osrm-backend/include/server/connection.hpp:5,
                 from /home/reza/projects/mobility_simulator/osrm-backend/include/server/server.hpp:4,
                 from /home/reza/projects/mobility_simulator/osrm-backend/src/tools/routed.cpp:1:
/home/linuxbrew/.linuxbrew/include/boost/bind.hpp:36:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
[ 82%] Linking CXX executable osrm-routed
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libboost_iostreams-mt.so.1.80.0: undefined reference to `fstat64@GLIBC_2.33'
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libboost_thread-mt.so.1.80.0: undefined reference to `pthread_key_create@GLIBC_2.34'
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libboost_thread-mt.so.1.80.0: undefined reference to `pthread_detach@GLIBC_2.34'
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libboost_thread-mt.so.1.80.0: undefined reference to `pthread_setspecific@GLIBC_2.34'
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/liblzma.so.5: undefined reference to `pthread_sigmask@GLIBC_2.32'
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libboost_thread-mt.so.1.80.0: undefined reference to `pthread_join@GLIBC_2.34'
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libboost_thread-mt.so.1.80.0: undefined reference to `pthread_getspecific@GLIBC_2.34'
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libboost_program_options-mt.so.1.80.0: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libboost_thread-mt.so.1.80.0: undefined reference to `pthread_condattr_setclock@GLIBC_2.34'
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libboost_thread-mt.so.1.80.0: undefined reference to `pthread_create@GLIBC_2.34'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/osrm-routed.dir/build.make:164: osrm-routed] Error 1
make[1]: *** [CMakeFiles/Makefile2:472: CMakeFiles/osrm-routed.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

I'd appreciate any help to resolve this issue.

**Comment by jcoupey** [comment]
What version of OSRM are your trying to build? For what it's worth the latest release v5.27.1 builds fine on Ubuntu 22.04.

**Comment by nilsnolde** [comment]
I just wonder what linuxbrew is, doesn’t sound like standard apt stuff.

**Comment by Rza-A** [comment]
> What version of OSRM are your trying to build? For what it's worth the latest release v5.27.1 builds fine on Ubuntu 22.04.

I am trying to build the latest version of the OSRM. Do you suggest to downgrade?



> I just wonder what linuxbrew is, doesn’t sound like standard apt stuff.

It is the *Homebrew* package manager paths. Initially I used *apt* to install the dependencies; I got similar error. Following some other instructions, it suggested to use brew to install the dependencies.

**Comment by SiarheiFedartsou** [comment]
You can try to use Conan (`-DENABLE_CONAN=ON`) - it allows to avoid dealing with any local deps

**Comment by nilsnolde** [comment]
You (or your nerves;)) might be best served using Docker, if you just want to run OSRM, not develop it.

**Comment by DennisOSRM** [comment]
Seems like pthread linker flag is not properly pressed to the compiler. But, yeah, docker build is perhaps the easiest way to build.

**Comment by Rza-A** [comment]
Thank you all for your help. I downgraded to v5.24.0, it compiled correctly.
