### ISSUE TITLE
Build error on Debian Wheezy

### ISSUE THREAD

**Issue by ondratu** [Project-OSRM/osrm-backend#1378]
Hi, I try tu build last master version v4.5.0, which is master on updated Debian Wheezy, but there are errors on build process. I build v4.4.0 successful. Thank's for help.

$ git branch
* master

$ git pull
Already up-to-date.

$ mkdir -p build; cd build; cmake ..; make

```
-- The C compiler identification is GNU 4.7.2
-- The CXX compiler identification is GNU 4.7.2
-- Check for working C compiler: /home/mcbig/bin/cc
-- Check for working C compiler: /home/mcbig/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/mcbig/bin/c++
-- Check for working CXX compiler: /home/mcbig/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Building on a 64 bit system
-- Configuring OSRM in release mode
-- Performing Test HAS_LTO_FLAG
-- Performing Test HAS_LTO_FLAG - Success
-- Performing Test HAS_COLOR_FLAG
-- Performing Test HAS_COLOR_FLAG - Failed
-- Boost version: 1.49.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   system
--   thread
--   unit_test_framework
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Intel TBB
-- Looking for Luabind...
-- Found Luabind: /usr/lib/libluabind.so  
-- Found Luabind: /usr/lib/libluabind.so
-- Could NOT find Lua52 (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR) 
-- Looking for LuaJIT 5.2
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR) 
-- Luabind/Lua5.2 not feasible, falling back to Lua 5.1.
-- Found Lua51: /usr/lib/x86_64-linux-gnu/liblua5.1.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.1.5") 
-- Looking for LuaJIT 5.1
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES LUAJIT_INCLUDE_DIR) 
-- Performing Test LUABIND51_WORKS
-- Performing Test LUABIND51_WORKS - Success
-- Luabind works with Lua 5.1 at /usr/lib/x86_64-linux-gnu/liblua5.1.so
-- Found EXPAT: /usr/lib/x86_64-linux-gnu/libexpat.so (found version "2.1.0") 
-- Looking for STXXL...
-- Found STXXL: /usr/lib/libstxxl.so  
-- Found STXXL: /usr/lib/libstxxl.so
-- Looking for OSMPBF...
-- Found OSMPBF: /usr/lib/libosmpbf.a  
-- Found OSMPBF: /usr/lib/libosmpbf.a
-- Found PROTOBUF: /usr/lib/libprotobuf.so  
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.7") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mcbig/develop/mapy-world/osrm-backend/build
Scanning dependencies of target COORDINATE
[  2%] Building CXX object CMakeFiles/COORDINATE.dir/data_structures/Coordinate.cpp.o
[  2%] Built target COORDINATE
Scanning dependencies of target EXCEPTION
[  5%] Building CXX object CMakeFiles/EXCEPTION.dir/Util/osrm_exception.cpp.o
[  5%] Built target EXCEPTION
Scanning dependencies of target FingerPrintConfigure
[  7%] Configuring finger_print.cpp
[  7%] Built target FingerPrintConfigure
Scanning dependencies of target FINGERPRINT
[ 10%] Configuring finger_print.cpp
[ 12%] Building CXX object CMakeFiles/FINGERPRINT.dir/Util/finger_print.cpp.o
[ 12%] Built target FINGERPRINT
Scanning dependencies of target GITDESCRIPTION
[ 15%] Building CXX object CMakeFiles/GITDESCRIPTION.dir/Util/git_sha.cpp.o
[ 15%] Built target GITDESCRIPTION
Scanning dependencies of target IMPORT
[ 17%] Building CXX object CMakeFiles/IMPORT.dir/data_structures/import_edge.cpp.o
[ 20%] Building CXX object CMakeFiles/IMPORT.dir/data_structures/external_memory_node.cpp.o
[ 20%] Built target IMPORT
Scanning dependencies of target LOGGER
[ 23%] Building CXX object CMakeFiles/LOGGER.dir/Util/simple_logger.cpp.o
[ 23%] Built target LOGGER
Scanning dependencies of target PHANTOMNODE
[ 25%] Building CXX object CMakeFiles/PHANTOMNODE.dir/data_structures/phantom_node.cpp.o
[ 25%] Built target PHANTOMNODE
Scanning dependencies of target OSRM
[ 28%] Building CXX object CMakeFiles/OSRM.dir/Library/OSRM_impl.cpp.o
In file included from /usr/include/c++/4.7/utility:72:0,
                 from /usr/include/boost/config/no_tr1/utility.hpp:21,
                 from /usr/include/boost/config/select_stdlib_config.hpp:37,
                 from /usr/include/boost/config.hpp:40,
                 from /usr/include/boost/filesystem.hpp:15,
                 from /home/mcbig/develop/mapy-world/osrm-backend/Include/osrm/ServerPaths.h:31,
                 from /home/mcbig/develop/mapy-world/osrm-backend/Library/OSRM_impl.h:35,
                 from /home/mcbig/develop/mapy-world/osrm-backend/Library/OSRM_impl.cpp:30:
/usr/include/c++/4.7/bits/stl_pair.h: In instantiation of ‘constexpr std::pair<_T1, _T2>::pair(const _T1&, const _T2&) [with _T1 = std::basic_string<char>; _T2 = GlobalTimer]’:
/usr/include/c++/4.7/bits/stl_pair.h:273:72:   required from ‘constexpr std::pair<typename std::__decay_and_strip<_T1>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&) [with _T1 = const std::basic_string<char>&; _T2 = GlobalTimer; typename std::__decay_and_strip<_T2>::__type = GlobalTimer; typename std::__decay_and_strip<_T1>::__type = std::basic_string<char>]’
/usr/include/c++/4.7/bits/hashtable_policy.h:445:24:   required from ‘std::__detail::_Map_base<_Key, _Pair, std::_Select1st<_Pair>, true, _Hashtable>::mapped_type& std::__detail::_Map_base<_Key, _Pair, std::_Select1st<_Pair>, true, _Hashtable>::operator[](const _Key&) [with _Key = std::basic_string<char>; _Pair = std::pair<const std::basic_string<char>, GlobalTimer>; _Hashtable = std::_Hashtable<std::basic_string<char>, std::pair<const std::basic_string<char>, GlobalTimer>, std::allocator<std::pair<const std::basic_string<char>, GlobalTimer> >, std::_Select1st<std::pair<const std::basic_string<char>, GlobalTimer> >, std::equal_to<std::basic_string<char> >, std::hash<std::basic_string<char> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, true, false, true>; std::__detail::_Map_base<_Key, _Pair, std::_Select1st<_Pair>, true, _Hashtable>::mapped_type = GlobalTimer]’
/home/mcbig/develop/mapy-world/osrm-backend/Library/../plugins/../Util/timing_util.hpp:55:30:   required from here
/usr/include/c++/4.7/bits/stl_pair.h:105:31: error: use of deleted function ‘GlobalTimer::GlobalTimer(const GlobalTimer&)’
In file included from /home/mcbig/develop/mapy-world/osrm-backend/Library/../plugins/distance_table.hpp:41:0,
                 from /home/mcbig/develop/mapy-world/osrm-backend/Library/OSRM_impl.cpp:37:
/home/mcbig/develop/mapy-world/osrm-backend/Library/../plugins/../Util/timing_util.hpp:37:8: note: ‘GlobalTimer::GlobalTimer(const GlobalTimer&)’ is implicitly deleted because the default definition would be ill-formed:
/home/mcbig/develop/mapy-world/osrm-backend/Library/../plugins/../Util/timing_util.hpp:37:8: error: use of deleted function ‘std::atomic<long unsigned int>::atomic(const std::atomic<long unsigned int>&)’
In file included from /usr/include/boost/asio/detail/atomic_count.hpp:23:0,
                 from /usr/include/boost/asio/detail/task_io_service.hpp:24,
                 from /usr/include/boost/asio/impl/io_service.hpp:71,
                 from /usr/include/boost/asio/io_service.hpp:767,
                 from /usr/include/boost/asio/basic_io_object.hpp:19,
                 from /usr/include/boost/asio/basic_socket.hpp:19,
                 from /usr/include/boost/asio/basic_datagram_socket.hpp:20,
                 from /usr/include/boost/asio.hpp:20,
                 from /home/mcbig/develop/mapy-world/osrm-backend/Include/osrm/Reply.h:33,
                 from /home/mcbig/develop/mapy-world/osrm-backend/Library/OSRM_impl.cpp:33:
/usr/include/c++/4.7/atomic:651:7: error: declared here
In file included from /usr/include/c++/4.7/utility:72:0,
                 from /usr/include/boost/config/no_tr1/utility.hpp:21,
                 from /usr/include/boost/config/select_stdlib_config.hpp:37,
                 from /usr/include/boost/config.hpp:40,
                 from /usr/include/boost/filesystem.hpp:15,
                 from /home/mcbig/develop/mapy-world/osrm-backend/Include/osrm/ServerPaths.h:31,
                 from /home/mcbig/develop/mapy-world/osrm-backend/Library/OSRM_impl.h:35,
                 from /home/mcbig/develop/mapy-world/osrm-backend/Library/OSRM_impl.cpp:30:
/usr/include/c++/4.7/bits/stl_pair.h: In instantiation of ‘constexpr std::pair<typename std::__decay_and_strip<_T1>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&) [with _T1 = const std::basic_string<char>&; _T2 = GlobalTimer; typename std::__decay_and_strip<_T2>::__type = GlobalTimer; typename std::__decay_and_strip<_T1>::__type = std::basic_string<char>]’:
/usr/include/c++/4.7/bits/hashtable_policy.h:445:24:   required from ‘std::__detail::_Map_base<_Key, _Pair, std::_Select1st<_Pair>, true, _Hashtable>::mapped_type& std::__detail::_Map_base<_Key, _Pair, std::_Select1st<_Pair>, true, _Hashtable>::operator[](const _Key&) [with _Key = std::basic_string<char>; _Pair = std::pair<const std::basic_string<char>, GlobalTimer>; _Hashtable = std::_Hashtable<std::basic_string<char>, std::pair<const std::basic_string<char>, GlobalTimer>, std::allocator<std::pair<const std::basic_string<char>, GlobalTimer> >, std::_Select1st<std::pair<const std::basic_string<char>, GlobalTimer> >, std::equal_to<std::basic_string<char> >, std::hash<std::basic_string<char> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, true, false, true>; std::__detail::_Map_base<_Key, _Pair, std::_Select1st<_Pair>, true, _Hashtable>::mapped_type = GlobalTimer]’
/home/mcbig/develop/mapy-world/osrm-backend/Library/../plugins/../Util/timing_util.hpp:55:30:   required from here
/usr/include/c++/4.7/bits/stl_pair.h:273:72: error: use of deleted function ‘constexpr std::pair<_T1, _T2>::pair(std::pair<_T1, _T2>&&) [with _T1 = std::basic_string<char>; _T2 = GlobalTimer; std::pair<_T1, _T2> = std::pair<std::basic_string<char>, GlobalTimer>]’
/usr/include/c++/4.7/bits/stl_pair.h:120:17: note: ‘constexpr std::pair<_T1, _T2>::pair(std::pair<_T1, _T2>&&) [with _T1 = std::basic_string<char>; _T2 = GlobalTimer; std::pair<_T1, _T2> = std::pair<std::basic_string<char>, GlobalTimer>]’ is implicitly deleted because the default definition would be ill-formed:
/usr/include/c++/4.7/bits/stl_pair.h:120:17: error: use of deleted function ‘GlobalTimer::GlobalTimer(const GlobalTimer&)’
make[2]: *** [CMakeFiles/OSRM.dir/Library/OSRM_impl.cpp.o] Error 1
make[1]: *** [CMakeFiles/OSRM.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by DennisOSRM** [comment]
```log
/usr/include/c++/4.7/bits/stl_pair.h:120:17: error: use of deleted function ‘GlobalTimer::GlobalTimer(const GlobalTimer&)’
```

It appears that you are trying to build using GCC 4.7. Support for this compiler was retired a number of months ago. Minimum build requirement is either GCC 4.8 or LLVM/Clang 3.3.
