### ISSUE TITLE
Windows builds are broken

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3088]
```
C:\projects\osrm\osrm-deps\boost\include\boost-1_59\boost/mpl/eval_if.hpp(41): error C2504: 'boost::result_of<const UnaryFunc (unsigned int &)>': base class undefined [C:\projects\osrm\build\ENGINE.vcxproj]
```

This was broken by #3015.

**Comment by oxidase** [comment]
@TheMarex  If #include <boost/range/adaptor/transformed.hpp> that is in assemble_leg.hpp
is included after
#include "engine/data_watchdog.hpp"
#include "storage/shared_barriers.hpp"
that include
#include <boost/detail/workaround.hpp>
#include <boost/interprocess/detail/workaround.hpp>
than something is going wrong, probably with forced inlines.

I can not reproduce the issue with 1.60 http://rextester.com/live/SZDL55018
I would suggest just to update boost in osrm-deps-win-x64-14.0.7z, and  there is still  a link issue with libboost_zlib-vc140-mt-1_59.lib

**Comment by oxidase** [comment]
@TheMarex just figured out the problem: in https://mapbox.s3.amazonaws.com/windows-builds/windows-build-deps/osrm-deps-win-x64-14.0.7z in file osrm-deps/boost/include/boost-1_59/boost/thread/lockable_traits.hpp contains `#define BOOST_NO_SFINAE` that breaks Boost.Range
It is a local modification, https://github.com/boostorg/thread/blob/develop/include/boost/thread/lockable_traits.hpp does not contain the line

**Comment by BergWerkGIS** [comment]
Yep, can/will fix. 😄 

Deps package gets created via [`windows-builds/scripts/build_osrm_deps.bat`](https://github.com/mapbox/windows-builds/blob/master/scripts/build_osrm_deps.bat)

**Comment by BergWerkGIS** [comment]
Updated `osrm-deps-win-x64-14.0.7z` to use `boost@1.61` without any modifications.

Now there's a different set of errors:
https://ci.appveyor.com/project/TheMarex/osrm-backend/build/1.0.3762

compared to the previous run:
https://ci.appveyor.com/project/TheMarex/osrm-backend/build/1.0.3761

**Comment by oxidase** [comment]
@BergWerkGIS The problem is in missing commit https://github.com/boostorg/config/commit/ea80234d5f1fff82573f7180f43b6600572fecc4
AppVeyor's MSVC is 190024215, so for 1.62 constant getters in Boost.Math will be defined as constexpr and it will compile.
 in 1.61 constexpr will be omitted as in `osrm-deps/boost/include/boost-1_61/boost/config/compiler/visualc.hpp`    unconditionally defined  `#define BOOST_NO_CXX11_CONSTEXPR`
Update 1.62 will not require osrm code changes but make minimal requirement for windows boost 1.62 and _MSC_FULL_VER >= 190024210

Another possibility is to  avoid constexpr and use BOOST_CONSTEXPR as
```
const BOOST_CONSTEXPR double MAXEXTENT = EARTH_RADIUS_WGS84 * boost::math::constants::pi<double>();
const BOOST_CONSTEXPR double DEGREE_TO_PX = detail::MAXEXTENT / 180.0;
```
that will fallback to `const double MAXEXTENT`.

**Comment by BergWerkGIS** [comment]
Updated to `boost@1.62`, error is now:
`CMake Warning:  Imported targets not available for Boost version`

https://ci.appveyor.com/project/TheMarex/osrm-backend/build/1.0.3788

**Comment by oxidase** [comment]
@BergWerkGIS thanks a lot! It works now without code changes.
Minimal requirements for windows:
* MSVC full version 190024210
* boost 1.62
* cmake 3.7.0

**Comment by daniel-j-h** [comment]
This got resolved.
